DROP TABLE t_se_usuario CASCADE CONSTRAINTS;
DROP TABLE t_se_motorista CASCADE CONSTRAINTS;
DROP TABLE t_se_empresa CASCADE CONSTRAINTS;
DROP TABLE t_se_carro CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_SE_USUARIO_RM;
DROP SEQUENCE SQ_SE_MOTORISTA;
DROP SEQUENCE SQ_SE_EMPRESA;
DROP SEQUENCE SQ_SE_CARRO;